import Head from "next/head";
import { useRouter } from "next/router";
import PageFornat from "../../Components/Common/PageFormat/PageFormat";
import PostPage from "../../Components/Pages/Post/PostPage";


const PostOuter = () => {
    const router = useRouter()
    const postID = router.query.postID
    return (
        <>
            <Head>
                <title>Post | {postID}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
             </Head>
             <PageFornat>
                <PostPage/>
             </PageFornat>
        </>
    );
}

export default PostOuter;