import Head from "next/head";
import { useRouter } from "next/router";
import PageFornat from "../../Components/Common/PageFormat/PageFormat";
import PostPage from "../../Components/Pages/Post/PostPage";
import {collection, getDocs, query, where} from 'firebase/firestore'
import {db} from '../../firebase/firebase'

const PostOuter = ({postData}) => {
    return (
        <>
            <Head>
                <title>{postData[0].title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
             </Head>
             <PageFornat>
                <PostPage postData={postData}/>
             </PageFornat>
        </>
    );
}

export async function getServerSideProps(context) {
  const collectionRef = collection(db, 'postData')
  const postID = context.params.postID
  const q = query(collection(db, "postData"), where('__name__', "==", postID));
  const rawData = await getDocs(q);
  const postData = rawData.docs.map(doc => ({
    postID: doc.id,
    imageURL: doc.data().imageURL,
    title: doc.data().title,
    about: doc.data().about,
    userName: doc.data().userName,
    text: doc.data().text
  })) 
  return {
    props: {
      postData,
    },
  }
}
  
export default PostOuter;