import Head from 'next/head'
import PageFormat from '../Components/Common/PageFormat/PageFormat'
import HomePage from '../Components/Pages/Home/HomePage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Loqui | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageFormat>
        <HomePage/>
      </PageFormat>
    </>
  )
}
